---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./config
    default_ttl: 3600
  cloudflare:
    class: octodns.provider.cloudflare.CloudflareProvider
    token: env/CLOUDFLARE_TOKEN

zones:
  phpdigest.ru.:
    sources:
      - config
    targets:
      - cloudflare